pages:
  - pisorgpl
  - MorawieckiPL
  - PlatformaObywatelska
  - donaldtusk
  - PL2050
  - szymonholowniaoficjalny
  - PetruRyszard
  - nowePSL
  - kosiniakkamysz
  - NowaaLewica
  - WlodzimierzCzarzasty
  - annamaria.zukowska
  - RobertBiedron
  - partiarazem
  - zandberg.razem
  - KONFEDERACJA2019
  - slawomirmentzen
  - krzysztofbosak.mikroblog
